version: '3'

services:
  nginx:
    container_name: reverse
    hostname: reverse
    build:
      context: nginx/
    ports:
      - "80:80"

  grafana:
    image: grafana/grafana-oss:8.2.6
    restart: always
  prometheus:
    image: prom/prometheus:v2.35.0
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"

  database:
    image: 'postgres:14'
    volumes:
      - ../db-data/:/var/lib/postgresql/data/
    env_file:
      - ../env/pg.env

  lte-exporter:
    image: "registry.gitlab.com/dekarl/fritzbox_exporter"
    env_file:
      - ../env/lte-export.env

  dsl-exporter:
    image: "registry.gitlab.com/dekarl/fritzbox_exporter"
    env_file:
      - ../env/dsl-export.env